# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Testing the builds

on:
  push:
    branches: [master, production]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12, 14]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
      - run: yarn test:coverage
      - uses: actions/checkout@v2
        if: matrix.node-version == 14 # only run coverage once
      - uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          file: ./coverage/Icov.info
